# 
- name: Add Grafana GPG key
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: 0644      
  when: ansible_os_family == "Debian"

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main
    state: present
    filename: grafana
  when: ansible_os_family == "Debian"

- name: Installer promtail package
  package:
    name: promtail
    state: present

- name: Add promtail user to docker group if exists
  user:
    name: promtail
    groups: docker
    append: yes
  when: docker_installed is true