---
# tasks file for promtail docker

- name: Get promtail user
  command: id -u promtail
  register: promtail_user
  failed_when: promtail_user.rc != 0
  changed_when: false

- name: Create variables for promtail user
  set_fact:
    promtail_user: "{{ promtail_user.stdout }}"

- name: Get logs-readers group
  shell: getent group logs-readers | cut -d ":" -f 3
  register: logs_readers_group
  failed_when: logs_readers_group.rc != 0
  changed_when: false

- name: Create variable for logs-readers group
  set_fact:
    logs_readers_group_id: "{{ logs_readers_group.stdout }}"

- name: Import docker compose template
  template:
    src: templates/docker-compose.yaml.j2
    dest: /opt/promtail/docker-compose.yaml
    mode: 0644
    owner: "{{ ansible_user }}"

- name: Start promtail service
  community.docker.docker_compose_v2:
    project_src: "/opt/promtail/"
    state: present